earthview_config_path: C:/Users/micha/Projects/EarthviewBackground/earthveiw_lib/config.json
earthview_data_path: C:/Users/micha/Projects/EarthviewBackground/earthview_scraper/results.json
monitors:
- \\?\DISPLAY#GSM7765#5&3b1fb7aa&0&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
- \\?\DISPLAY#GSM7765#5&3b1fb7aa&0&UID4357#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
